version: 2

jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn clean install

  workflows:
    main:
      jobs:
        - build-and-test
